# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import kv_pb2 as proto_dot_kv__pb2


class KeyValueStoreStub(object):
    """RPCs for key-value server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetData = channel.unary_unary(
            '/kvstore.KeyValueStore/GetData',
            request_serializer=proto_dot_kv__pb2.GetRequest.SerializeToString,
            response_deserializer=proto_dot_kv__pb2.GetResponse.FromString,
        )
        self.PutData = channel.unary_unary(
            '/kvstore.KeyValueStore/PutData',
            request_serializer=proto_dot_kv__pb2.PutRequest.SerializeToString,
            response_deserializer=proto_dot_kv__pb2.PutResponse.FromString,
        )


class KeyValueStoreServicer(object):
    """RPCs for key-value server
    """

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetData': grpc.unary_unary_rpc_method_handler(
            servicer.GetData,
            request_deserializer=proto_dot_kv__pb2.GetRequest.FromString,
            response_serializer=proto_dot_kv__pb2.GetResponse.SerializeToString,
        ),
        'PutData': grpc.unary_unary_rpc_method_handler(
            servicer.PutData,
            request_deserializer=proto_dot_kv__pb2.PutRequest.FromString,
            response_serializer=proto_dot_kv__pb2.PutResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'kvstore.KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """RPCs for key-value server
    """

    @staticmethod
    def GetData(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KeyValueStore/GetData',
                                             proto_dot_kv__pb2.GetRequest.SerializeToString,
                                             proto_dot_kv__pb2.GetResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutData(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KeyValueStore/PutData',
                                             proto_dot_kv__pb2.PutRequest.SerializeToString,
                                             proto_dot_kv__pb2.PutResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
