# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/kv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eproto/kv.proto\x12\x07kvstore\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0bPutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x7f\n\rKeyValueStore\x12\x36\n\x07GetData\x12\x13.kvstore.GetRequest\x1a\x14.kvstore.GetResponse\"\x00\x12\x36\n\x07PutData\x12\x13.kvstore.PutRequest\x1a\x14.kvstore.PutResponse\"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.kv_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_GETREQUEST']._serialized_start = 27
    _globals['_GETREQUEST']._serialized_end = 52
    _globals['_GETRESPONSE']._serialized_start = 54
    _globals['_GETRESPONSE']._serialized_end = 82
    _globals['_PUTREQUEST']._serialized_start = 84
    _globals['_PUTREQUEST']._serialized_end = 124
    _globals['_PUTRESPONSE']._serialized_start = 126
    _globals['_PUTRESPONSE']._serialized_end = 156
    _globals['_KEYVALUESTORE']._serialized_start = 158
    _globals['_KEYVALUESTORE']._serialized_end = 285
# @@protoc_insertion_point(module_scope)
